export const usersPreload = [
  {
    id: 1,
    profileImg: "https://i.ibb.co/hxNwS8F/perfil1.png",
    name: "Juan",
    lastName: "Pérez",
    city: "Madrid",
    country: "España",
    description: "Ingeniero de software con experiencia en desarrollo web.",
    skills: ["JavaScript", "React", "Node.js"],
  },
  {
    id: 2,
    profileImg: "https://i.ibb.co/SJNWsDh/perfil5.png",
    name: "María",
    lastName: "González",
    country: "España",
    city: "Barcelona",
    description: "Diseñadora gráfica enfocada en UX/UI.",
    skills: ["Photoshop", "Illustrator", "Figma", "Sketch"],
  },
  {
    id: 3,
    profileImg: "https://i.ibb.co/wNTkQfF/perfil2.png",
    name: "Carlos",
    lastName: "Rodríguez",
    country: "España",
    city: "Valencia",
    description: "Especialista en marketing digital y redes sociales.",
    skills: ["SEO", "SEM", "Google Analytics", "Content Marketing"],
  },
  {
    id: 4,
    profileImg: "https://i.ibb.co/zFtrf49/perfil4.png",
    name: "Ana",
    lastName: "Martínez",
    country: "España",
    city: "Sevilla",
    description: "Desarrolladora backend con pasión por los datos.",
    skills: ["Python", "Django", "SQL", "NoSQL"],
  },
  {
    id: 5,
    profileImg: "https://i.ibb.co/xgGNh8t/perfil3.png",
    name: "Luis",
    lastName: "Fernández",
    country: "España",
    city: "Bilbao",
    description: "Analista de datos con experiencia en BI.",
    skills: ["Excel", "Power BI", "Tableau", "SQL", "R"],
  },
];
